# Generated by Django 3.0.7 on 2020-06-11 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200611_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regi_key',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
    ]
