# Generated by Django 3.0.7 on 2020-06-21 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0012_remove_service_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('total_sale', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale_services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(blank=True, default=None, null=True)),
                ('cli', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.Client')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Sales')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Service')),
            ],
        ),
    ]
