# Generated by Django 3.0.7 on 2020-06-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_remove_service_profit'),
        ('sales', '0002_auto_20200621_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale_services',
            name='service',
        ),
        migrations.CreateModel(
            name='Services_for_sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Sale_services')),
                ('ser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Service')),
            ],
        ),
    ]
