# Generated by Django 3.0.7 on 2020-06-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20200623_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale_services',
            name='final_price',
        ),
        migrations.AddField(
            model_name='sale_services',
            name='services',
            field=models.CharField(default='null', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale_services',
            name='true_price',
            field=models.IntegerField(default=None),
        ),
        migrations.DeleteModel(
            name='Services_for_sale',
        ),
    ]
