# Generated by Django 3.0.7 on 2020-06-23 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20200623_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale_services',
            name='sales',
        ),
        migrations.AddField(
            model_name='sale_services',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
