# Generated by Django 3.0.7 on 2020-06-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20200623_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_services',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
