# Generated by Django 3.0.7 on 2020-06-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20200613_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_slots',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
