# Generated by Django 3.0.7 on 2020-06-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_time_slots_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_slots',
            name='time_booked',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
