# Generated by Django 3.0.7 on 2020-06-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20200613_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_slots',
            name='time_booked',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
