# Generated by Django 3.0.7 on 2020-06-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20200613_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_slots',
            name='time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
