# Generated by Django 3.0.7 on 2020-06-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_time_slots_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_slots',
            name='time',
        ),
    ]
