# Generated by Django 3.0.7 on 2020-06-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_remove_time_slots_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
