# Generated by Django 3.0.7 on 2020-06-21 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Time_slots',
            new_name='TimeSlots',
        ),
    ]
