# Generated by Django 3.0.7 on 2020-06-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_remove_service_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='anniversery',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
