# Generated by Django 3.0.7 on 2020-07-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_auto_20200703_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
