# Generated by Django 3.0.7 on 2020-07-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_auto_20200703_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='cli',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='confirmation',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='work_to_be_done',
        ),
        migrations.AddField(
            model_name='appointment',
            name='test',
            field=models.CharField(default='test', max_length=10, null=True),
        ),
    ]
