# Generated by Django 3.0.7 on 2020-07-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_auto_20200703_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='test',
        ),
    ]
