# Generated by Django 3.0.7 on 2020-07-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0020_auto_20200703_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='anniversery',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
