# Generated by Django 3.0.7 on 2020-07-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0022_auto_20200703_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time_taken',
            field=models.IntegerField(default=None, null=True),
            preserve_default=False,
        ),
    ]
