# Generated by Django 3.0.7 on 2020-07-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0023_service_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time_taken',
            field=models.IntegerField(null=True),
        ),
    ]
