# Generated by Django 3.0.7 on 2020-07-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0026_service_time_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='time_taken',
        ),
    ]
